# This is an example configuration file for EPAB.
# 
# Version: 2018.10.29.1.
# 
# WARNING: this example file will be overwritten every time EPAB starts.
# Make sure to save your work and rename the file when you are done!
# 
# It must be renamed to "pyproject.toml" in order to come into effect.
# 
# The configuration file follows the TOML format specification.
# 
# Mandatory and optional values
# =============================
# 
# Some values are mandatory, some aren't. Mandatory values are marked with the "MANDATORY VALUE" tag. If mandatory values
# are missing, EPAB will not start.
# 
# Note that, while not necessary for EPAB to function, failing to provide non-mandatory values may prevent 
# non-essential modules to start.
# 
# OS environment
# ==============
# 
# All configuration values may also be given using the OS environment instead of the config file. However, 
# the "EPAB_" prefix must be added (this is to prevent any potential conflict with other application.
# 
# For example, the configuration "dummy_key: dummy_value" would be set in the OS environment using the variable
# "EPAB_DUMMY_KEY=dummy_value".
# 
# Values types
# =============
# 
# Value types will be checked at runtime.
# 
# TOML specification
# ==================
# 
# The full TOML specification can be found at: https://github.com/toml-lang/toml
# 
# Here's an example taken from the readme:
# 
# ####################################################################
# # This is a TOML document.
# 
# title = "TOML Example"
# 
# [owner]
# name = "Tom Preston-Werner"
# dob = 1979-05-27T07:32:00-08:00 # First class dates
# 
# [database]
# server = "192.168.1.1"
# ports = [ 8001, 8001, 8002 ]
# connection_max = 5000
# enabled = true
# 
# [servers]
# 
#   # Indentation (tabs and/or spaces) is allowed but not required
#   [servers.alpha]
#   ip = "10.0.0.1"
#   dc = "eqdc10"
# 
#   [servers.beta]
#   ip = "10.0.0.2"
#   dc = "eqdc10"
# 
# [clients]
# data = [ ["gamma", "delta"], [1, 2] ]
# 
# # Line breaks are OK when inside arrays
# hosts = [
#   "alpha",
#   "omega"
# ]
# ####################################################################
# 
# 
# START OF ACTUAL CONFIG FILE

[tool]
[tool.epab]
package_name = "epab_test"
[tool.epab.appveyor]
# List of artifacts for Appveyor
# value type: array of strings
# Array elements must be type: string
# example = ["a", "b", "c", "d e"] # A list of strings
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# artifacts = []

# Additional command line options for tests run on AV
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# test_runner_options = "--long"


[tool.epab.changelog]
# Disable changelog building
# value type: boolean
# "true" and "false" are the only valid boolean values
# example = true
# example = false
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# disable = false

# Path to changelog file
# value type: path (must be a file)
# WARNING: backslash characters ("\") must be doubled.
# Alternatively, you can use the forward slash: "/" (even on Windows).
# example = c:\\some\\folder
# example = c:\\some\\folder\\file.ext
# example = c:/this/is/valid/too
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# file_path = "CHANGELOG.rst"


[tool.epab.doc]
# Local documentation directory
# value type: path (must be a directory)
# WARNING: backslash characters ("\") must be doubled.
# Alternatively, you can use the forward slash: "/" (even on Windows).
# example = c:\\some\\folder
# example = c:\\some\\folder\\file.ext
# example = c:/this/is/valid/too
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# folder = "./doc"

# Documentation repository on Github
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# repo = ""


[tool.epab.freeze]
# PyInstaller data-files list
# value type: array of strings
# Array elements must be type: string
# example = ["a", "b", "c", "d e"] # A list of strings
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# data_files = []

# Main entry point for pyinstaller
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# entry_point = ""


[tool.epab.lint]
# List of comma separated files for flake8 to exclude
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# flake8_exclude = ""

# Linter max line width
# value type: integer
# example = 10
# example = 0
# example = -5
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# line_length = 120

# Additional MyPy arguments
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# mypy_args = ""

# Package name
# value type: string
# example = "some text inside double quotes"
# MANDATORY CONFIG VALUE: you *must* provide a value for this setting
# 


[tool.epab.qt]
# Qt resource file (.qrc) location
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# res_src = ""

# Compiled Qt resource file (.py) target location
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# res_tgt = ""

# Less console output
# value type: boolean
# "true" and "false" are the only valid boolean values
# example = true
# example = false
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# quiet = false


[tool.epab.test]
# Minimal coverage to pass tests
# value type: integer
# example = 10
# example = 0
# example = -5
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# coverage_fail_under = 20

# Amount of "slow" tests to show
# value type: integer
# example = 10
# example = 0
# example = -5
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# duration_count = 10

# Additional options for test run
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# runner_options = ""

# Target of pytest
# value type: string
# example = "some text inside double quotes"
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# target = "test"

# Timeout in seconds for pytest runner
# value type: integer
# example = 10
# example = 0
# example = -5
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# timeout = 300

# More console output
# value type: boolean
# "true" and "false" are the only valid boolean values
# example = true
# example = false
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
# 
# verbose = false

[tool.epab.graph]
# Generate graphs using PyReverse
# value type: boolean
# "true" and "false" are the only valid boolean values
# example = true
# example = false
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
#
make = false

[tool.epab.twine]
# Upload package to Twine after build
# value type: boolean
# "true" and "false" are the only valid boolean values
# example = true
# example = false
# Setting this value is not required; you can leave it commented out.
# The default value (the one that will be used if you do not provide another) is shown below:
#
upload = false

